### ISSUE TITLE
Setup script does not properly initialize the database

### ISSUE THREAD

**Issue by aimxhaisse** [scaleway-community/scaleway-wordpress#17]
The following:

    for i in {1..10}
    do
        scw start $(scw create wordpress)
        sleep 10
    done

Out of 10 servers, 2 have a:

    Error establishing a database connection

On one of the problematic servers:

    root@modest-bell:~# mysql -uroot -pXXX
    ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
    root@modest-bell:~# ps aux | grep mysql
    mysql     2197  0.2  1.6 319152 35084 ?        Ssl  07:54   0:01 /usr/sbin/mysqld

Weird...

    root@modest-bell:/var/log/upstart# /etc/init.d/mysql restart
     * Stopping MySQL database server mysqld                                                                                                                                    [ OK ]
     * Starting MySQL database server mysqld                                                                                                                                    [fail]

Looks like it can't start, that's because stop fails:

    root@modest-bell:/var/log/mysql# /etc/init.d/mysql stop
     * Stopping MySQL database server mysqld                                                                                                                                    [ OK ]
    root@modest-bell:/var/log/mysql# ps aux | grep mysql
    mysql     2197  0.2  1.6 319152 35084 ?        Ssl  07:54   0:02 /usr/sbin/mysqld
    root      4266  0.0  0.0   1392   484 pts/1    S    08:09   0:00 /bin/sh /usr/bin/mysqld_safe
    mysql     4613  0.2  1.2 278616 26144 pts/1    Sl   08:09   0:00 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --log-error=/var/log/mysql/error.log --pid-file=/var/run/mysqld/mysqld.pid --socket=/var/run/mysqld/mysqld.sock --port=3306

Tried to force kill:

    root@modest-bell:/var/log/mysql# pkill -9 mysql
    root@modest-bell:/var/log/mysql# /etc/init.d/mysql start
     * Starting MySQL database server mysqld                                                                                                                                    [ OK ]

Then it worked.

Could be related to:

    mysql.log:/usr/bin/mysqladmin: connect to server at 'localhost' failed
    mysql.log:error: 'Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)'
    mysql.log:Check that mysqld is running and that the socket: '/var/run/mysqld/mysqld.sock' exists!
    mysql.log:mysqld is alive

**Comment by edouardb** [comment]
This should be fixed since c292168
